### ISSUE TITLE
Undefined symbols for architecture x86_64: "_libscrypt_scrypt" (macOS)

### ISSUE THREAD

**Issue by delta1** [MagicalBitcoin/libtor#19]
Hi @afilini ! I am having a compilation issue I hope you can help with.  

I am using `libtor` in a new rust project with the example in [the docs](https://docs.rs/libtor/46.6.0+0.4.6.6/libtor/), however `cargo build` on macOS 11.5.2 fails with this error: 

```
Undefined symbols for architecture x86_64:
            "_libscrypt_scrypt", referenced from:
                _secret_to_key_compute_key in libtor_sys-87ae6f5a3fd58264.rlib(libtor_crypt_ops_a-crypto_s2k.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I cloned `libtor` and `libtor-sys` and both repos can build successfully on their own, but as I say in a new rust project using `libtor` as a dependency I am facing this linking issue. 

Any ideas? Your help is greatly appreciated. Thanks!

```rust
# main.rs 
use libtor::{HiddenServiceVersion, Tor, TorAddress, TorFlag};

fn main() {
    match Tor::new()
        .flag(TorFlag::DataDirectory("/tmp/tor-rust".into()))
        .flag(TorFlag::SocksPort(19050))
        .flag(TorFlag::HiddenServiceDir("/tmp/tor-rust/hs-dir".into()))
        .flag(TorFlag::HiddenServiceVersion(HiddenServiceVersion::V3))
        .flag(TorFlag::HiddenServicePort(
            TorAddress::Port(8000),
            None.into(),
        ))
        .start()
    {
        Ok(r) => println!("{}", r),
        Err(e) => eprintln!("{}", e),
    }
}
```

```toml
# Cargo.toml
[package]
name = "tor"
version = "0.1.0"
edition = "2018"

[dependencies]
libtor = "46.6.0+0.4.6.6"
```

**Comment by delta1** [comment]
update here: 

Tor release notes pointed to openssl having an implementation of libscrypt as well - after removing the system installation of openssl (`brew uninstall openssl`) I was able to compile successfully using your `vendored-openssl` feature. 

I would still like to find a way to compile this without vendoring openssl, since the libscrypt dep is optional for Tor from what I understand. Will investigate further when I can.

**Comment by afilini** [comment]
This should be fixed in the latest libtor-sys release (running `cargo update` should be enough to pull it in). Feel free to reopen if the error persists.

**Comment by delta1** [comment]
Thanks! Confirmed :+1:
