### ISSUE TITLE
generate_hashed_password does not always work

### ISSUE THREAD

**Issue by lucasbaizer2** [MagicalBitcoin/libtor#24]
I was coming across a strange bug where `generate_hashed_password` wouldn't work, seeming at random. Passing the same password to generate_hashed_password and running Tor would sometimes give me this output from Tor:
```
Jan 05 00:40:03.613 [warn] Failed to parse/validate config: Bad HashedControlSessionPassword: wrong length or bad encoding
```

After some digging, it looks like this error does actually happen literally at random!
https://github.com/MagicalBitcoin/libtor/blob/master/libtor/src/lib.rs#L428

The hex digits are not zero-padded, so values less than 16 are encoded as e.x. `f` instead of `0f`. Changing the format code to `{:02x}` should fix this. It also needs to be done on the final line of the function as well:
https://github.com/MagicalBitcoin/libtor/blob/master/libtor/src/lib.rs#L431

**Comment by afilini** [comment]
Thanks for spotting this, will fix and release a new version soon
