### ISSUE TITLE
Android return code 255

### ISSUE THREAD

**Issue by Marekkon5** [MagicalBitcoin/libtor#26]
Hello, I use the following code:

```
let r = Tor::new()
                .flag(TorFlag::LogTo(LogLevel::Info, LogDestination::Stdout))
                .flag(TorFlag::SocksPort(port))
                .start();
            info!("Tor Start: {:?}", r);
```

Which works perfectly fine on PC, however running it on Android results in `255` process exit code (from the `.start()` function).

Has this been tested on Android? Is there some way to redirect the log to the `log` library, because I can't access the stdout log on Android (file doesn't work either)?. Thanks

**Comment by afilini** [comment]
It has been tested on android, maybe you are not allowed to start listening on that specific port? Double check your manifest permissions to make sure this is not the problem.

Also tor needs a datadir to store stuff, I'm not sure what the default is but it may not be good for android. Try specifying a custom datadir set to a path that you know is writable (ideally the private storage of your app).

You can also log to logcat, there's a specific variant for it: `LogDestination::Android`. I'm afraid it's not shown in the docs because it's only enabled when targeting android, but [it's there](https://docs.rs/libtor/latest/src/libtor/log.rs.html#25).

**Comment by afilini** [comment]
You should also be able to log to file I think, just make sure the path is writable.

**Comment by Marekkon5** [comment]
I've tried log to file on `/sdcard/log.log` which was 100% writable coz I was able to File::create it. I'll try the Android LogDestination, because I didn't notice earlier. Which are all the config options affecting data/socket dirs I have to change? Thanks

**Comment by afilini** [comment]
I think just the `TorFlag::DataDirectory()` should be fine to begin

**Comment by Marekkon5** [comment]
I've tried your suggestions, but nothing helped. There is also nothing new in the log - nothing Tor related. Return code is also 255.

My code:
```
let mut tor = Tor::new();

#[cfg(target_os = "android")]
tor.flag(TorFlag::LogTo(LogLevel::Info, LogDestination::Android));

std::fs::File::create("/data/user/0/<APP>/cache/test.txt").unwrap();

let r = tor
    .flag(TorFlag::SocksPort(port))
    .flag(TorFlag::DataDirectory("/data/user/0/<APP>/cache".to_string()))
    .start();
info!("Tor Start: {:?}", r);
```

1. The file create is there to double check if the directory is writable (it is)
2. The return from `.start()`: `Ok(255)`
3. I've tried few different ports in the 20-40K range
4. It is running inside a thread (normal `std::thread::spawn`)
5. Permissions:
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

Logcat of Rust:
```
<unknown>: Starting tor with args: [
     "tor",
     "Log",
     "info android",
     "SocksPort",
     "26666",
     "DataDirectory",
     "/data/user/0/com.marekkon5.ncflu/cache",
]
<unknown>: Tor Start: Ok(255)
```


Do you have any more suggestions or things I could try? Or ways that I could at least access the log? Or some example project? Thank you.

**Comment by Marekkon5** [comment]
Okay so, I was able to make another project where I ran it as binary, and capture the stdout. Few things to note:

1. I got error with the android log level - it said it's invalid value / failed to parse config.
2. You have to set the `HOME` env variable to **existing** folder
3. The only option I've set in the end was SocksPort to get it working. DataDir etc should work too.
