### ISSUE TITLE
Signal handling

### ISSUE THREAD

**Issue by straylight-orbit** [MagicalBitcoin/libtor#27]
When pressing CTRL+C in a foreground process that started Tor, the following message appears: `[notice] Interrupt: exiting cleanly.`

It immediately shuts down Tor with no possibility of catching the signal and doing an orderly shutdown. Established TCP connections immediately break. Is there a way of overriding this behavior and making Tor ignore the signal so that we can perform our own shutdown procedure?

**Comment by afilini** [comment]
You can enable `__DisableSignalHandlers` either in your torrc or in the command line args. It's not well documented but you can find it mentioned here: https://gitlab.torproject.org/tpo/core/torspec/-/blob/main/control-spec.txt#L3941-3953
