### ISSUE TITLE
How to map local address:port to hidden service port?

### ISSUE THREAD

**Issue by Jikstra** [MagicalBitcoin/libtor#7]
I want to map a locally running http server on 127.0.0.1:8080 to the hidden service on port 80.
This would be the following config line: `HiddenServicePort 80 127.0.0.1:8080`.
In libtor i expect it with `.flag(TorFlag::HiddenServicePort(TorAddress::Port(80), TorAddress::AddressPort("127.0.0.1".into(), 8080)))` bust rust complains with following error:

```
38 |         .flag(TorFlag::HiddenServicePort(TorAddress::Port(80), TorAddress::AddressPort("127.0.0.1".into(), 8080)))
   |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `libtor::utils::DisplayOption`, found enum `TorAddress`
   |
   = note: expected struct `libtor::utils::DisplayOption<TorAddress>`
                found enum `TorAddress`

```

I cannot wrap it in DisplayOption as it's a private struct/method in libtor. Any suggestions?

**Comment by Jikstra** [comment]
Okay i had to make utils public and then I could do it with this code:
`.flag(TorFlag::HiddenServicePort(TorAddress::Port(80), DisplayOption::from(Some(TorAddress::AddressPort("127.0.0.1".into(), 8080)) )))`

**Comment by afilini** [comment]
`DisplayOption<T>` should implement `From<Option<T>>`, so you can just use `.into()` without having to make it public:

```rust
.flag(TorFlag::HiddenServicePort(TorAddress::Port(80), Some(TorAddress::AddressPort("127.0.0.1".into(), 8080).into())))
```

**Comment by Jikstra** [comment]
@afilini thanks for the response, sadly this doesn't compile for me:
```
error[E0308]: mismatched types
  --> src/main.rs:40:64
   |
40 |         .flag(TorFlag::HiddenServicePort(TorAddress::Port(80), Some(TorAddress::AddressPort("127.0.0.1".into(), 8080).into())))
   |                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `libtor::utils::DisplayOption`, found enum `Option`
   |
   = note: expected struct `libtor::utils::DisplayOption<TorAddress>`
                found enum `Option<_>`

error: aborting due to 2 previous errors; 2 warnings emitted
```
